# Generated by Django 4.0.4 on 2022-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
