# Generated by Django 4.0.4 on 2022-06-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(default=False, max_length=255, null=''),
        ),
    ]
