# Generated by Django 4.0.4 on 2022-06-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lake', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('boat_rating', models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High')], default='ME', max_length=2)),
                ('boat_type', models.CharField(choices=[('PO', 'Pontoon'), ('FI', 'Fishing'), ('CH', 'Charterfishing'), ('JE', 'Jetski'), ('SP', 'Speedboat')], default='PO', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
