# Generated by Django 4.0.4 on 2022-06-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_boat_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='test',
        ),
    ]
