# Generated by Django 4.0.4 on 2022-06-09 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0003_remove_boat_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'is_owner': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boat',
            name='renter',
            field=models.ForeignKey(limit_choices_to={'is_renter': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
    ]
