# Generated by Django 4.0.4 on 2022-06-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_alter_boat_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(choices=[('PO', 'Pontoon'), ('CH', 'Charterfishing'), ('JE', 'Jetski'), ('SP', 'Speedboat'), ('FI', 'Fishing')], default='PO', max_length=2),
        ),
    ]
