# Generated by Django 4.0.4 on 2022-06-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_alter_boat_boat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
