# Generated by Django 4.0.4 on 2022-06-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_alter_boat_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(max_length=100),
        ),
    ]
