# Generated by Django 4.0.4 on 2022-06-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0009_alter_boat_boat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='day',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='end_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active status'),
        ),
        migrations.AddField(
            model_name='boat',
            name='start_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
