# Generated by Django 4.0.4 on 2022-06-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_boat_day_boat_end_time_boat_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='day',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='start_time',
        ),
        migrations.AddField(
            model_name='boat',
            name='option_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='option_three',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='option_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
