# Generated by Django 4.0.4 on 2022-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_remove_boat_day_remove_boat_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='boat_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
