# Generated by Django 4.0.4 on 2022-06-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0012_boat_boat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='renter_selection',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
