# Generated by Django 4.0.4 on 2022-06-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0013_boat_renter_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='active status'),
        ),
    ]
