# Generated by Django 4.0.4 on 2022-06-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0014_alter_boat_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='is_active',
            field=models.BooleanField(default=False, null='', verbose_name='active status'),
        ),
    ]
