# Generated by Django 4.0.4 on 2022-07-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0015_alter_boat_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='lake',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
