# Generated by Django 4.0.4 on 2022-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0016_alter_boat_boat_rating_alter_boat_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
