# Generated by Django 4.0.4 on 2022-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0017_alter_boat_boat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
