# Generated by Django 4.0.4 on 2022-06-13 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0007_alter_boat_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LentBoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.boat')),
                ('renter', models.ForeignKey(limit_choices_to={'is_renter': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boat_renter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
