# Generated by Django 4.0.4 on 2022-06-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lentboats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lentboat',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'is_owner': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boat_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
