# Generated by Django 4.0.4 on 2022-06-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lentboats', '0003_lentboat_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lentboat',
            name='owner',
        ),
    ]
