# Generated by Django 4.0.4 on 2022-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentboats', '0004_remove_lentboat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lentboat',
            name='day',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lentboat',
            name='end_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lentboat',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
    ]
